//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.19 at 10:39:56 AM EDT 
//


package com.citi.cs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workflowHeader" type="{transaction}batchInformationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workflowHeader"
})
@XmlRootElement(name = "transaction")
public class Transaction {

    @XmlElement(required = true)
    protected BatchInformationType workflowHeader;

    /**
     * Gets the value of the workflowHeader property.
     * 
     * @return
     *     possible object is
     *     {@link BatchInformationType }
     *     
     */
    public BatchInformationType getWorkflowHeader() {
        return workflowHeader;
    }

    /**
     * Sets the value of the workflowHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchInformationType }
     *     
     */
    public void setWorkflowHeader(BatchInformationType value) {
        this.workflowHeader = value;
    }

}
